# prueba para que se desplieugue algo : Version 1.0.0.1
replicaCount: 1
image:
  repository: ghcr.io/vachocalla/sintv3-app
  pullPolicy: Always
  tag: "231d435" #latest

service:
  type: ClusterIP
  port: 8090
  targetPort: 8080
